# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NIT_7.1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NIT_7.1
  pod 'Nuke', '~> 9.0'

  target 'NIT_7.1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NIT_7.1UITests' do
    # Pods for testing
  end

end
